apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orocommerce.fullname" . }}-nginx
  labels:
    {{- include "orocommerce.labels" . | nindent 4 }}
data:
  default.conf: |
{{- tpl (.Files.Get "files/default.conf.template") . | nindent 4 }}
{{- if .Values.robots.noindex }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orocommerce.fullname" . }}-robots
  labels:
    {{- include "orocommerce.labels" . | nindent 4 }}
data:
  robots.txt: |
    User-agent: *
    Disallow: /
{{- end }}
