{{- $ctx := dict "Chart" .Chart "Release" .Release "Values" .Values "component" "cron" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "orocommerce.fullname" . }}-cron
  labels:
    {{- include "orocommerce.componentLabels" $ctx | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.cron }}
  selector:
    matchLabels:
      {{- include "orocommerce.componentSelectorLabels" $ctx | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "orocommerce.componentSelectorLabels" $ctx | nindent 8 }}
    spec:
      initContainers:
        {{- include "orocommerce.waitBootstrapInit" . | nindent 8 }}
      containers:
        - name: cron
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/bin/ofelia", "daemon", "--config", "/etc/ofelia.conf"]
          env:
            {{- include "orocommerce.appEnv" . | nindent 12 }}
          volumeMounts:
            {{- include "orocommerce.appVolumeMounts" . | nindent 12 }}
          resources:
            {{- toYaml .Values.resources.cron | nindent 12 }}
      volumes:
        {{- include "orocommerce.appVolumes" . | nindent 8 }}
